### PR TITLE
Feature/jstassi/#75 #76 updates

### PR DESCRIPTION
**Pull request by gmao-jstassi**
Updates to 
1. use logical directory path for FVROOT rather than physical (absolute) path
2. add -partition and -qos options to monthly.yyyymm.pl.tmpl

### CODE REVIEW

**Review by rtodling — APPROVED** [review]
These look good by me.

**Comment by rtodling** [comment]
Joe, I am having problems w/ fvsetup in this - fvsetup itself seems to work - but I cannot xxdiff it (or diff it) w/ any other version of fvsetup since the one here comes up as a binary file! Really odd. Can you please look into this?

**Review by rtodling — APPROVED** [review]
Changes are already in develop - rt-GEOSadas-5_28_0_p1

**Comment by rtodling** [comment]
Changes are already in develop - rt-GEOSadas-5_28_0_p1

**Comment by gmao-jstassi** [comment]
Ricardo,

Sorry about this. I hope you remembered that I was on vacation from last Wednesday through yesterday. We drove down to Alabama for my aunt's 90th birthday, with stops in Gatlinburg, Tennessee, on the way down and in Pilot Mountain, North Carolina, on the way home. I took my computer with me, but we were so busy that I never even turned it on.

The problem is a stray non-ascii character in line 2288 in fvsetup. I found it by doing xxdiff with the --text flag. I have updated my tag locally but am not sure how to push the change back to the central repository.

You can find a copy on the updated fvsetup in /discover/nobackup/jstassi/RTodling

Joe

________________________________
From: rtodling ***@***.***>
Sent: Wednesday, June 2, 2021 9:02 AM
To: GEOS-ESM/GEOSadas ***@***.***>
Cc: Stassi, Joe (GSFC-610.1)[SCIENCE SYSTEMS AND APPLICATIONS INC] ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [GEOS-ESM/GEOSadas] Feature/jstassi/#75 #76 updates (#85)


Joe, I am having problems w/ fvsetup in this - fvsetup itself seems to work - but I cannot xxdiff it (or diff it) w/ any other version of fvsetup since the one here comes up as a binary file! Really odd. Can you please look into this?

**Pull request closed without merging**
