### PR TITLE
Add slurm-array options to ensemble ADAS

### PR DESCRIPTION
**Pull request by rtodling**
This adds the option to distribute jobs in the ADAS ensemble using slurm-arrays - there are is still some odd behavior sometimes - but resubmit seems to work ok.

Also updated components.yaml

This also updates resource files and bring things to version 6.11.1 of the model.

### CODE REVIEW

**Review by mathomp4 — DISMISSED** [review]

**Comment by mathomp4** [comment]
Hmm. I might need to push a fix to your CI. I think it's now out-of-date with the updates in this...

**Comment by mathomp4** [comment]
@rtodling If you want this now, let me know and I can force it in over the CI objections.

**Comment by rtodling** [comment]
@mathomp4 Any idea why this is failing in the build?

**Review by mathomp4 — DISMISSED** [review]

**Comment by mathomp4** [comment]
> @mathomp4 Any idea why this is failing in the build?

@rtodling Yeah. It's an issue with f2py in CI, because f2py is *very* twitchy and really only works on NCCS at most. 

The "fixes" include a new tag of GMAOpyobs that I hope to get out next week when Patricia is back (v1.0.6.1) where I can add a CMake variable to not build f2py in CI. For now, feel free to merge this in. Once I can get that f2py fix in, then I can work on getting things working.

PS: It's also hitting a bug I found in GMAO_Shared (see https://github.com/GEOS-ESM/GMAO_Shared/pull/352), but that's sort of on me as in my CI testing I mistakenly used a newer compiler. But CI is just stuck until I can get that new GMAOpyobs to you.

**Review by mathomp4 — APPROVED** [review]

**Pull request merged**
