### PR TITLE
Fix up ADAS CI

### PR DESCRIPTION
**Pull request by mathomp4**
This PR attempts to fix the ADAS CI. The changes are:

1. Update to GMAOpyobs v1.0.6.1 which allows for not building `f2py` code in CI (see https://github.com/GEOS-ESM/GMAOpyobs/compare/v1.0.6...v1.0.6.1)
2. Backs off the circleci-tools orb to v2.10 which is before Intel 2021.13 came in

### CODE REVIEW

**Comment by mathomp4** [comment]
It worked! Yay!

**Comment by rtodling** [comment]
@mathomp4  Why does this take so long to run the CI tests?

**Comment by mathomp4** [comment]
> @mathomp4 Why does this take so long to run the CI tests?

Huh. I did not notice that. Something must be wonky. Let me take a look...

**Comment by mathomp4** [comment]
I just tried a push of a quick fix. I don't think it's perfect, but should make the build faster I hope.

**Comment by rtodling** [comment]
> I just tried a push of a quick fix. I don't think it's perfect, but should make the build faster I hope.



> I just tried a push of a quick fix. I don't think it's perfect, but should make the build faster I hope.

ok - thank you.

**Comment by mathomp4** [comment]
> > I just tried a push of a quick fix. I don't think it's perfect, but should make the build faster I hope.
> 
> ok - thank you.

The "real" issue seems to be the compiler in CI land is dying trying to compile a file...but then it works the next time around. Obviously the file compiles on discover, etc., so my only thought is maybe I just need less make parallelism for that one file (i.e., compiler running out of memory?). Fingers crossed!

**Comment by rtodling** [comment]
hum - that's odd - that's no happened to me once ... and I have compiled numerous times. perhaps the compilation in the CI is not quite one-to-one w/ how things get compiled in actuality, could that be?

**Review by rtodling — APPROVED** [review]
This seems good by me. Thank you.

**Pull request merged**
