### PR TITLE
Add Ocean-LETKF 

### PR DESCRIPTION
**Pull request by sanAkel**
This PR: 
- Replaces currently _unused_ [UMD_Etc](https://github.com/GEOS-ESM/UMD_Etc) with [Ocean-LETKF](https://github.com/GEOS-ESM/Ocean-LETKF) that is (more) actively being developed.

It is a _structural_ change and **does not change any answers.**

### CODE REVIEW

**Review by tclune — DISMISSED** [review]
cmake changes ok

**Review by rtodling — DISMISSED** [review]
Seem ok by me.

**Comment by sanAkel** [comment]
@mathomp4 Maybe the test is because of some repo dependency?

**Comment by mathomp4** [comment]
Oh. I see. No, I'm trying to figure out how to get CircleCI to build the GEOSadas on PR in #245 but it's just not working yet. 

This PR can be pulled in by @rtodling as it doesn't require the CI. GitHub just won't turn the "Merge pull request" button green.

I'm giving the CI one last chance. If it doesn't work, I think the only way I can get it to work is by modularizing all of GSI and...that's too much work.

**Comment by rtodling** [comment]
Why did this fail? Santha - something is wrong in what you passed me ... or did I mess up in the merge?

**Comment by sanAkel** [comment]
> Why did this fail? Santha - something is wrong in what you passed me ... or did I mess up in the merge?

@rtodling I have to punt this!

@mathomp4, Something in baselibs? I do recall you saying something about the _right_ HDF5. The build that I have, with @mathomp4's help used following baselibs.
> /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.7/x86_64-pc-linux-gnu/ifort_2021.2.0-intelmpi_2021.2.0

**Comment by mathomp4** [comment]
> > Why did this fail? Santha - something is wrong in what you passed me ... or did I mess up in the merge?
> 
> @rtodling I have to punt this!
> 
> @mathomp4, Something in baselibs? I do recall you saying something about the _right_ HDF5. The build that I have, with @mathomp4's help used following baselibs.
> 
> > /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.7/x86_64-pc-linux-gnu/ifort_2021.2.0-intelmpi_2021.2.0

I think there are a couple things we can do:

1. In our fork of Ocean-LETKF, you have a branch, [`feature/sanAkel/to_build_within_GEOS`](https://github.com/GEOS-ESM/Ocean-LETKF/tree/feature/sanAkel/to_build_within_GEOS) that has some CMake changes we made to let Ocean-LETKF work with GEOS' build system. That branch seems to be out-of-date with `main` but it could be brought up to date (to capture work by @gmao-cda) and we could work off of that branch.
2. I am currently testing a change to ESMA_cmake that might fix this by adding support for an `HDF5::HDF5` CMake target. I've tested it and it will *build* everything in Ocean-LETKF (which frankly would satisfy myself and @rtodling), but I don't know how to *run* any of this code, so it's possible there might be issues.

@sanAkel if I update your branch to point to my CMake change, can you build and test this GEOSadas branch to make sure things build and any Ocean-LETKF executables run?

**Comment by sanAkel** [comment]
> > > Why did this fail? Santha - something is wrong in what you passed me ... or did I mess up in the merge?
> 
> > 
> 
> > @rtodling I have to punt this!
> 
> > 
> 
> > @mathomp4, Something in baselibs? I do recall you saying something about the _right_ HDF5. The build that I have, with @mathomp4's help used following baselibs.
> 
> > 
> 
> > > /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.2.7/x86_64-pc-linux-gnu/ifort_2021.2.0-intelmpi_2021.2.0
> 
> 
> 
> I think there are a couple things we can do:
> 
> 
> 
> 1. In our fork of Ocean-LETKF, you have a branch, [`feature/sanAkel/to_build_within_GEOS`](https://github.com/GEOS-ESM/Ocean-LETKF/tree/feature/sanAkel/to_build_within_GEOS) that has some CMake changes we made to let Ocean-LETKF work with GEOS' build system. That branch seems to be out-of-date with `main` but it could be brought up to date (to capture work by @gmao-cda) and we could work off of that branch.
> 
> 2. I am currently testing a change to ESMA_cmake that might fix this by adding support for an `HDF5::HDF5` CMake target. I've tested it and it will *build* everything in Ocean-LETKF (which frankly would satisfy myself and @rtodling), but I don't know how to *run* any of this code, so it's possible there might be issues.
> 
> 
> 
> @sanAkel if I update your branch to point to my CMake change, can you build and test this GEOSadas branch to make sure things build and any Ocean-LETKF executables run? 

@mathomp4 Thank you!

Please push and let me know.

**Comment by mathomp4** [comment]
> > @sanAkel if I update your branch to point to my CMake change, can you build and test this GEOSadas branch to make sure things build and any Ocean-LETKF executables run?
> 
> @mathomp4 Thank you!
> 
> Please push and let me know.

@sanAkel I've updated your branch here. I think it should build. Can you clone-and-build and try out any executables you need?

**Comment by rtodling** [comment]
Still something failing ...

**Comment by gmao-cda** [comment]
Hi @mathomp4 , if this will make it easier, I can build the Ocean-LETKF as a standalone on Discover using the esma baselibs with the version (`/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-7.5.0/x86_64-pc-linux-gnu/ifort_2021.6.0-intelmpi_2021.6.0`). 
The commands are:
```
cd Ocean-LETKF && mkdir cbuild && cd cbuild

cmake .. -DCMAKE_Fortran_COMPILER=ifort -DSOLO_BUILD=on -DMODEL=mom6 \
-DCMAKE_INCLUDE_PATH="$BASEDIR/Linux/include/netcdf;$BASEDIR/Linux/include/hdf5" \
-DCMAKE_LIBRARY_PATH="$BASEDIR/Linux/lib"

make
```

all executables are under `cbuild/src/`.

My preloaded module on discover are 
```
Currently Loaded Modules:
  1) git/2.39.2          6) git-lfs/3.2.0     11) comp/intel/2021.6.0
  2) cmake/3.23.1        7) other/gh          12) mpi/impi/2021.6.0
  3) other/mepo          8) other/tree/2.1.0  13) python/GEOSpyD/Min4.11.0_py3.9_AND_Min4.8.3_py2.7
  4) other/tig/2.5.4     9) GEOSenv
  5) ImageMagick/7.1.0  10) comp/gcc/10.3.0
```
by sourcing `/discover/nobackup/projects/gmao/scda_iesa/cda/GEOSgcm_08Nov2022/@env/g5modules.sh`

the latest commit of this GEOSgcm is 
```
commit 8be8c0c6143f4d07c8c1d92b21bc9f4248e52321 (HEAD -> main, origin/main, origin/HEAD)
Merge: ff991d4 63349a3
Author: Scott Rabenhorst <53346946+sdrabenh@users.noreply.github.com>
Date:   Tue Nov 1 09:30:43 2022 -0400

    Merge pull request #476 from GEOS-ESM/feature/mathomp4/update-esma-env-4.5.0

    Update ESMA_env to v4.5.0 and ESMA_cmake to v3.19.0
```


Also, I added a build test under the ocean-letkf (https://github.com/GEOS-ESM/Ocean-LETKF/actions ), and the latest successful building was triggered by Matt (`matt-test-build`) about 4 hours ago. 

@mathomp4 Is there any shared latest ESMA baselibs available on Discover? I can check if I can build ocean-letkf using that baselibs

**Comment by mathomp4** [comment]
> Still something failing ...

@rtodling the CI build succeeded. But I added a blocking label to this until Santha can do a test

@gmao-cda the `matt-test-build` branch was my attempt at merging `main` into [`feature/sanAkel/to_build_within_GEOS`](https://github.com/GEOS-ESM/Ocean-LETKF/tree/feature/sanAkel/to_build_within_GEOS) which was something @sanAkel and me made a while back which changes the CMake in Ocean-LETKF to work with Baselibs. But this PR uses `main` directly instead of that branch so I guess it's the branch wanted. So I updated ESMA_cmake to try and support `main`

**Comment by sanAkel** [comment]
Thanks @mathomp4, it's good for me: `git clone -b feature/sanAkel/to_build_Ocean-LETKF-within_GEOS  git@github.com:GEOS-ESM/GEOSadas.git`

>discover14.sakella 1029> ll build/bin/GEOS*
-rwxr-xr-x 1 sakella s2647 135M Feb 21 11:33 build/bin/GEOSgcm.x*
-rwxr-xr-x 1 sakella s2647  41M Feb 21 11:28 build/bin/GEOSgcmPert.x*
discover14.sakella 1030> ll build/bin/GSI*
-rwxr-xr-x 1 sakella s2647 92M Feb 21 11:29 build/bin/GSIsa.x*

>/discover/nobackup/projects/gmao/scda_iesa/sakella/da/ana/21Feb2023/GEOSadas
discover14.sakella 1037> l install/bin/*letkf*
-rwxr-xr-x 1 sakella s2647 14M Feb 21 11:01 install/bin/OCN.letkf_mom6.x*


@rtodling, can it be merged now?

**Review by rtodling — APPROVED** [review]
Ok, let's give it another try ... approving now.

**Comment by rtodling** [comment]
This is NOT working!! 

see log file from parallel run from off develop ...
/gpfsm/dnb05/projects/p61/rtodling/4OPS/g530x/GEOSadas/ 

I want to revert this commit ...

**Comment by gmao-cda** [comment]
Hi @mathomp4 , would you please explain how does GEOS build pass the compiler flags to different repos (e.g., OCEAN-LETKF, and other repos)?
If I assigned `CMAKE_Fortran_FLAGS`, `CMAKE_Fortran_FLAGS_DEBUG`, `CMAKE_Fortran_FLAGS_RELEASE` under the `OCEAN-LETKF`, will they be passed to the next repo following `OCEAN-LETKF` as shown in the `components.yaml`?

In the OCEAN-LETKF, I have a section modifying compiling flags based on compiler vendor
```
    # compiler-dependent flags   
    if (CMAKE_Fortran_COMPILER_ID MATCHES "GNU")
        set(CMAKE_Fortran_FLAGS "-O2 -ffree-line-length-none -frecord-marker=4 -finit-local-zero -fbacktrace")
        set(CMAKE_Fortran_FLAGS_DEBUG "-O0 -ffree-line-length-none -frecord-marker=4 -finit-local-zero -fbacktrace -fcheck=mem,pointer,bounds -fno-realloc-lhs")
        set(CMAKE_Fortran_FLAGS_RELEASE "-O3 -ffree-line-length-none -frecord-marker=4 -finit-local-zero")
        ## additional flags for gfortran version >= 10.0
        if (${CMAKE_Fortran_COMPILER_VERSION} VERSION_GREATER_EQUAL 10) 
           set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -fallow-argument-mismatch -fallow-invalid-boz")
        endif ()
    elseif (CMAKE_Fortran_COMPILER_ID MATCHES "Intel")
        set(CMAKE_Fortran_FLAGS "-O2 -g -traceback")
        set(CMAKE_Fortran_FLAGS_DEBUG "-O0 -traceback -check bounds")
        set(CMAKE_Fortran_FLAGS_RELEASE "-O3")
    endif()
```
See codes at https://github.com/GEOS-ESM/Ocean-LETKF/blob/1eb214cba736b7e173cdd25a1caeb9df82ab84cf/CMakeLists.txt#L33-L45

I'm wondering whether this causes the building error.

**Comment by mathomp4** [comment]
@gmao-cda If you build Ocean-LETKF inside GEOSadas, then you pass into the "else" of that file:
```cmake
else() # build as an application with GEOS-ESM infra
    message(STATUS "OCEAN-LETKF: SOLO_BUILD=${SOLO_BUILD}, build with GEOS-ESM infra")
endif()
```
so you are now using the flags we set in ESMA_cmake:

https://github.com/GEOS-ESM/ESMA_cmake/tree/main/compiler/flags

**Comment by sanAkel** [comment]
> /gpfsm/dnb05/projects/p61/rtodling/4OPS/g530x/GEOSadas/

@rtodling check your disk quota:

> CMake Error at src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/@GEOSchem_GridComp/@GMI/cmake_install.cmake:64 (file):
  **file INSTALL cannot copy file**
  "/discover/nobackup/projects/gmao/advda/rtodling/4OPS/g530x/GEOSadas/build/src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/@GEOSchem_GridComp/@GMI/Deposition_Registry___.rc"
  to
  "/discover/nobackup/projects/gmao/advda/rtodling/4OPS/g530x/GEOSadas/install/etc/Deposition_Registry___.rc":
  **Disk quota exceeded.
Call Stack (most recent call first):**
  src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/@GEOSchem_GridComp/cmake_install.cmake:67 (include)
  src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/cmake_install.cmake:55 (include)
  src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/cmake_install.cmake:56 (include)
  src/Components/@GEOSgcm_GridComp/cmake_install.cmake:82 (include)
  src/Components/cmake_install.cmake:47 (include)
  src/cmake_install.cmake:48 (include)
  cmake_install.cmake:60 (include)

**Comment by rtodling** [comment]
My bad ...the disk I was under got full ... all good. Thank you.

**Pull request merged**
