### PR TITLE
Modify code to allow resetting max BUFR record through an environment variable

### PR DESCRIPTION
**Pull request by gmao-msienkie**
Modified the routines in NCEP_Paqc which write new information to ADPUPA (radiosonde) records.  If a sounding has a large number of levels, the modifications made to the records may cause them to be larger than the maximum BUFR record size, and that sounding record will be discarded.  The previous maximum record size (set by 'call maxout') was 15000, which is adequate for most soundings.  (An occasional sounding record is still being dropped in the MERRA2 assimilation, and these long soundings also appear to be missing from the gdas.prepbufr files.)
In the IGRA2 processing the number of levels in a raob sounding was reduced to 250 or less, which produced records small enough to fit in the original BUFR record size.   However, during a 'sweeper' test of IGRA data one sounding created an 'overlarge subset' (bufr record too large) after the RADCOR processing and the sounding was discarded.  
While we could go back in the programs and bump up the maximum record size again, it would more convenient to be able to adjust the maximum record without having to recompile all the affected programs - hence the addition of a method to increase the bufr record size by modifying the environment variable BUFR_MAXOUT.  If the environment variable is not set, the maximum record size will be set to 15000 as before.

### CODE REVIEW

**Comment by gmao-msienkie** [comment]
Zero diff if environment variable is not set, or if environment variable is set to the current bufr record size or lower.  
Zero diff if the input prepbufr file does not have any long soundings which create overlarge records after additional QC information is added.
Non-zero diff if environment variable is set to a larger bufr values.  QC decisions will be the same for input files that did not generate any overlarge records; the bufr record size will just be different.  (For single level data the library will pack in observations into a record until the maximum size is reached.)  QC decisions will be different in e.g. OIQC if a previously dropped record is retained after the maximum bufr record size is increased.

**Comment by gmao-msienkie** [comment]
This is more oriented for R21C but similar changes might be useful for MERRA2.  We have one or two 'overlarge subset' reports every month or so in the MERRA2 prepqc.log files

**Comment by gmao-msienkie** [comment]
I have been monitoring the various runs (sweeper, GEOSIT and of course MERRA2) and with the current settings were are dropping a sounding every so often.  It seems like maybe it is a little more frequent as time goes by.  Though of course with GEOSIT we'll be switching the the NCEP gdas.prepbufr input files at the end of 2021 (I think) and will be letting the NCEP processing drop the overlong soundings instead.
Here are the results of a scan of the prepqc.log files from GEOSIT:
d5294_geosit_jan18/etc> grep -c 'OVERLARGE SUBSET' Y*/M*/*prepqc.log* | grep -v 't:0'
Y2017/M01/d5294_geosit_jan18.prepqc.log.20170116_00z-20170116_21z.txt:1
Y2017/M06/d5294_geosit_jan18.prepqc.log.20170617_00z-20170617_21z.txt:1
Y2017/M10/d5294_geosit_jan18.prepqc.log.20171022_00z-20171022_21z.txt:1
Y2017/M11/d5294_geosit_jan18.prepqc.log.20171106_00z-20171106_21z.txt:1
Y2018/M02/d5294_geosit_jan18.prepqc.log.20180207_00z-20180207_21z.txt:1
Y2018/M04/d5294_geosit_jan18.prepqc.log.20180402_00z-20180402_21z.txt:1
Y2018/M05/d5294_geosit_jan18.prepqc.log.20180511_00z-20180511_21z.txt:1
Y2018/M06/d5294_geosit_jan18.prepqc.log.20180623_00z-20180623_21z.txt:1
Y2018/M07/d5294_geosit_jan18.prepqc.log.20180709_00z-20180709_21z.txt:1
Y2018/M07/d5294_geosit_jan18.prepqc.log.20180720_00z-20180720_21z.txt:1
Y2018/M10/d5294_geosit_jan18.prepqc.log.20181026_00z-20181026_21z.txt:1
Y2018/M11/d5294_geosit_jan18.prepqc.log.20181124_00z-20181124_21z.txt:1
Y2019/M02/d5294_geosit_jan18.prepqc.log.20190205_00z-20190205_21z.txt:1
Y2019/M02/d5294_geosit_jan18.prepqc.log.20190208_00z-20190208_21z.txt:1
Y2019/M02/d5294_geosit_jan18.prepqc.log.20190209_00z-20190209_21z.txt:2
Y2019/M02/d5294_geosit_jan18.prepqc.log.20190210_00z-20190210_21z.txt:1
Y2019/M02/d5294_geosit_jan18.prepqc.log.20190211_00z-20190211_21z.txt:2
Y2019/M02/d5294_geosit_jan18.prepqc.log.20190214_00z-20190214_21z.txt:1
Y2019/M04/d5294_geosit_jan18.prepqc.log.20190414_00z-20190414_21z.txt:1
Y2019/M07/d5294_geosit_jan18.prepqc.log.20190730_00z-20190730_21z.txt:1
Y2019/M08/d5294_geosit_jan18.prepqc.log.20190815_00z-20190815_21z.txt:1
Y2019/M08/d5294_geosit_jan18.prepqc.log.20190821_00z-20190821_21z.txt:2
Y2019/M09/d5294_geosit_jan18.prepqc.log.20190904_00z-20190904_21z.txt:1

**Comment by gmao-msienkie** [comment]
I decided to add the 'zero diff' label since as explained above this would almost always be zero-diff unless the environment variable feature is used to prevent overlarge records from being dropped in the prepQC processing.

**Review by rtodling — APPROVED** [review]
This seem good by me.

**Pull request merged**
