### PR TITLE
Use CMake to ignore build and install directories

### PR DESCRIPTION
**Pull request by mathomp4**
A la https://github.com/GEOS-ESM/GEOSgcm/pull/258, use CMake itself to ignore build and install directories rather than assuming all build and install directories will be named `build` and `install`.

### CODE REVIEW

**Review by tclune — APPROVED** [review]

**Comment by rtodling** [comment]
This seems fine to me.

**Review by rtodling — APPROVED** [review]

**Comment by rtodling** [comment]
BTW: 

Whatever writes the sentence:
All required statuses and check runs on this pull request must run successfully to enable automatic merging.
Could be revised to read:
All required statuses and check runs on this pull request must run successful to enable automatic merging.

**Comment by rtodling** [comment]
Oh my .. that was a foolish comment ... I misread the line - please forgive me

**Comment by rtodling** [comment]
The question is why does this show: All checks have failed?

**Comment by tclune** [comment]
It shows "all" checks have failed because the 1 check we are requiring has failed.    Something do do with the required-labels.    I can guess that there is something wrong with the implementation of the "Needs Lead Approval" label, as presumably that would mean @rtodling, who has in fact approved.   So back to @mathomp4

**Comment by mathomp4** [comment]
I guess I was leaving the "Needs Lead Approval" removal to @rtodling, but as he approves, I removed it. 

That said, I wonder if there is a way to remove that label on approval...hmm... 🤔

**Pull request merged**
