### PR TITLE
GCM is a bit more general than just `AGCM`

### PR DESCRIPTION
**Pull request by sanAkel**
The header `Run the GCM` needs to reflect the fact that `gcm_setup` sets up not only `AGCM`

### CODE REVIEW

**Comment by mathomp4** [comment]
Question: Can you actually run the OGCM in what's in `GEOSadas-5_27_1_p3`? I know we can in the GEOSgcm for sure, but does it work in the ADAS tag?

**Comment by sanAkel** [comment]
> Question: Can you actually run the OGCM in what's in `GEOSadas-5_27_1_p3`? I know we can in the GEOSgcm for sure, but does it work in the ADAS tag?

@mathomp4 I would have to clone, build and check. Will try sometime ... and report _here_.

**Comment by rtodling** [comment]
Santha: can you change this so that the PR is to merge onto develop instead of main? 
The workflow I want for the DAS is user -> develop -> main
The Edit button next to the PR title allows you to redirect the request (I learned it from Matt)

**Review by rtodling — COMMENTED** [review]
I already changed this line to read 
Running GCM

**Comment by rtodling** [comment]
I suggest we simply close this ticket

**Comment by rtodling** [comment]
BTW: the change is still sitting in my work dir since I have another change and have not committed things yet - but I will.

**Comment by sanAkel** [comment]
> I suggest we simply close this ticket

@rtodling,
I have no problem closing the **draft** PR.

However, I did follow up on above [promise](https://github.com/GEOS-ESM/GEOSadas/pull/56#issuecomment-786804128):
1. cloned: `git clone git@github.com:GEOS-ESM/GEOSadas.git`
2. build: `./parallel_build.csh -tmpdir /tmp` the `-tmpdir /tmp` is because of some intel _bug_ that @mathomp4 told me! He would know better.
3. [set up a coupled model exp from scratch](https://github.com/GEOS-ESM/GEOSadas/#run-the-agcm): with `gcm_setup` but clearly did not work since my experiment directory only has:
```
GEOSgcm.x*
RC/
sedfile
SETENV.commands
```

Which leads me to ask:
- What would you want to do? **Fix** `gcm_setup` which probably would get fixed as [adas components.yaml](https://github.com/GEOS-ESM/GEOSadas/blob/develop/components.yaml) gets _caught_ up with gcm components.yaml https://github.com/GEOS-ESM/GEOSadas/issues/53#issuecomment-786826446 ?
- Set up a coupled model exp from `gcm_forecast.setup`?

Either way, we must check GCM = `AGCM` or `AOGCM`?

**Comment by sanAkel** [comment]
For what its worth, following is the STDOUT from `gcm_setup`:

```
discover15.sakella 179> gcm_setup 

Enter the Experiment ID:
test_MM
Enter a 1-line Experiment Description:
test_mom5_adas
Do you wish to CLONE an old experiment? (Default: NO or FALSE)

Enter the Atmospheric Horizontal Resolution code:
-----------------------------------------------------------
     Lat/Lon                     Cubed-Sphere
-----------------------------------------------------------
   b --  2  deg                c48  --  2   deg 
   c --  1  deg                c90  --  1   deg 
   d -- 1/2 deg                c180 -- 1/2  deg (56-km) 
   e -- 1/4 deg (35-km)        c360 -- 1/4  deg (28-km)  
   c720 -- 1/8  deg (14-km) 
   c1440 - 1/16 deg ( 7-km) 
             DYAMOND Grids                 
   c768 -- 1/8  deg (12-km) 
   c1536 - 1/16 deg ( 6-km) 
   c3072 - 1/32 deg ( 3-km) 
 
c90
Enter the Atmospheric Model Vertical Resolution: LM (Default: 72)

Do you wish to run the COUPLED Ocean/Sea-Ice Model? (Default: NO or FALSE)
YES

Enter the Ocean Lat/Lon Horizontal Resolution: IM JM (Default: 360 200)

Enter the Ocean Model Vertical Resolution: LM (Default: 50)

Enter the choice of  Land Surface Boundary Conditions using: 1 (Default: Icarus), 2 (Latest Icarus-NL)


Do you wish to run  the Runoff Routing Model? (Default: NO or FALSE)

Do you wish to run GOCART with Actual or Climatological Aerosols? (Enter: A (Default) or C)


Enter the GOCART Emission Files to use: MERRA2 (Default), PIESA, CMIP, NR, MERRA2-DD or OPS:

Enter the directory (/filename) of the HISTORY.AGCM.rc.tmpl to use
(To use HISTORY.AGCM.rc.tmpl from current build, Type:  Current         )
-------------------------------------------------------------------------
Hit ENTER to use Default Location: (HISTORY.AOGCM.rc.tmpl)

 
Enter Desired Location for the HOME Directory (to contain scripts and RC files)
Hit ENTER to use Default Location:
----------------------------------
Default:  /discover/nobackup/sakella/test_MM


Enter Desired Location for the EXPERIMENT Directory (to contain model output and restart files)
Hit ENTER to use Default Location:
----------------------------------
Default:  /discover/nobackup/sakella/test_MM

Enter Location for Build directory containing:  bin/ etc/ include/ etc...
Hit ENTER to use Default Location:
----------------------------------
Default:  /gpfsm/dnb32/sakella/geosDas/develop_04Mar2021/GEOSadas/install

 
Current GROUPS: g0613 s0818 s2313 soca gmaoint advda m2val
Enter your GROUP ID for Current EXP: (Default: advda)
-----------------------------------

sending incremental file list
GEOSgcm.x

sent 210,883,578 bytes  received 35 bytes  60,252,460.86 bytes/sec
total size is 210,832,000  speedup is 1.00
OCEAN_NAME: Undefined variable.
```

So it died for `OCEAN_NAME` which is either MOM (=MOM5 by default) or `MOM6` which was added to `gcm_setup` in some version of GEOSgcm. Probably _this_ version of ADAS does not use it (yet). That's my guess. @mathomp4 would you agree?

**Comment by rtodling** [comment]
Santha: shouldn't I wait to get these updates when we actually have a version of the Git ADAS that pulls the coupled model?

**Comment by sanAkel** [comment]
> Santha: shouldn't I wait to get these updates when we actually have a version of the Git ADAS that pulls the coupled model?

@rtodling I don't think there is anything missing, in other words, 
>Git ADAS that pulls the coupled model?
I think already happens! Certainly for the coupled model with MOM5 ocean model. What seems messed up is the stuff in https://github.com/GEOS-ESM/GEOSadas/blob/3163e9fbf9dc78d0601c7a6af07bbed2a8ce17f0/components.yaml#L95-L99 which as seem to say, will get updated. 

For that reason, I didn't feel like closing this PR, but leave it as is in draft. So it serves as a reminder for me to check again. Is that okay with you?

**Comment by rtodling** [comment]
That's fine Santha

**Comment by mathomp4** [comment]
Fixed in `develop`.

**Pull request closed without merging**
