### PR TITLE
R21C: Additional change related to python3 stuff

### PR DESCRIPTION
**Pull request by rtodling**
All seems to work for AOD analysis  on Milan (wrt python 3 updates).

These are not guarantee to be zero diff though I have seen cases in which the changes are zero diff.

### CODE REVIEW

**Comment by rtodling** [comment]
Need final official tag on MAPL to be able to turn this from draft to actual PR.

**Review by mathomp4 — DISMISSED** [review]

**Comment by rtodling** [comment]
@mathomp4 do you please to tag MAPL from 

release/2.35.3+R21C_v1.4.0 to

v2.35.3+R21C_v1.4.0 

?

**Comment by mathomp4** [comment]
> @mathomp4 do you please to tag MAPL from
> 
> release/2.35.3+R21C_v1.4.0 to
> 
> v2.35.3+R21C_v1.4.0
> 
> ?

@rtodling It should be there now:

https://github.com/GEOS-ESM/MAPL/releases/tag/v2.35.3%2BR21C_v1.4.0

**Comment by rtodling** [comment]
> > @mathomp4 do you please to tag MAPL from
> > release/2.35.3+R21C_v1.4.0 to
> > v2.35.3+R21C_v1.4.0
> > ?
> 
> @rtodling It should be there now:
> 
> https://github.com/GEOS-ESM/MAPL/releases/tag/v2.35.3%2BR21C_v1.4.0

Thank you!

**Comment by rtodling** [comment]
@mathomp4 All seems to have completed here, but still not letting me finish the PR. Can you please have a look? Sorry.

**Comment by rtodling** [comment]
Perhaps it  needs a reviewer ... if you could pls.

**Review by mathomp4 — APPROVED** [review]

**Comment by rtodling** [comment]
Thank you!

**Comment by mathomp4** [comment]
> Perhaps it needs a reviewer ... if you could pls.

Yeah. I guess an update staled my review.

**Pull request merged**
