### PR TITLE
Logic was added to pass the ARCHIVE location from GEOSadas to the Pyr…

### PR DESCRIPTION
**Pull request by gmao-jstassi**
…admon code so that it has the correct location when GEOSadas is not using the default location. This update also contains the $datamove_constraint variable and related logic from Ricardo which he was planning to add later. He said that including it now would have no impact.

### CODE REVIEW

**Review by rtodling — APPROVED** [review]
Thanks Joe

**Comment by rtodling** [comment]
Hum ... I just realize this will break the system for most people ... you committed the props dastest lines as uncommented lines ... they need to be commented out.

**Comment by rtodling** [comment]
Unfortunately, I approved this before noticing ... will need a fix

**Comment by gmao-jstassi** [comment]
Hi Ricardo,

Sorry about that. I took the updates that I found in Mohar's version of the file. I thought that they had come from you.

Let me know when you make the commitment so that I can update my version.

Thanks!
Joe

________________________________
From: rtodling ***@***.***>
Sent: Monday, October 4, 2021 2:34 PM
To: GEOS-ESM/GEOSadas ***@***.***>
Cc: Stassi, Joe (GSFC-610.1)[SCIENCE SYSTEMS AND APPLICATIONS INC] ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [GEOS-ESM/GEOSadas] Logic was added to pass the ARCHIVE location from GEOSadas to the Pyr… (#112)


Hum ... I just realize this will break the system for most people ... you committed the props dastest lines as uncommented lines ... they need to be commented out.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FGEOSadas%2Fpull%2F112%23issuecomment-933748066&data=04%7C01%7Cjoe.stassi%40nasa.gov%7Ce464c4d8fb9849d33eff08d987659897%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637689692691865089%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7BdXnDrOLSBO5zfjy14KDOTsZCd1tOhffMAwUkeRF8w%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMBAJ2XC7G77YIUJ73N3GRLUFHXS7ANCNFSM5EIFV5QA&data=04%7C01%7Cjoe.stassi%40nasa.gov%7Ce464c4d8fb9849d33eff08d987659897%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637689692691875048%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2yjozkgYny7A45sbg8dfzGOznSHAefEAD%2Fc%2BqQ%2BTUy4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjoe.stassi%40nasa.gov%7Ce464c4d8fb9849d33eff08d987659897%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637689692691884996%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yvKhSDpfqniCsQsQuCSac2oLTaPvsvVP71zkdqrTGsE%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjoe.stassi%40nasa.gov%7Ce464c4d8fb9849d33eff08d987659897%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637689692691884996%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mKLErBTqutGp7qavJStm%2F%2BBYO9%2BBYHxx6gE3EHbvPoM%3D&reserved=0>.

**Pull request merged**
