### PR TITLE
Feature/jstassi/#73 integrate radmon into adas

### PR DESCRIPTION
**Pull request by gmao-jstassi**
This pull request must be done in conjunction with a pull request in GMAO_Shared to get new script echorc.pl

### CODE REVIEW

**Comment by mathomp4** [comment]
@gmao-jstassi I think you started this with an *old* version of GEOSadas as it's trying to change a *LOT*.

You might have to redo your branch basing it off of `develop` at present.

**Comment by gmao-jstassi** [comment]
Matt,

I think I started with Ricardo's version. That might be the problem. Maybe I shouldn't have made a pull request but just given the branch info to Ricardo?

Is that the problem?

Joe

________________________________
From: Matthew Thompson ***@***.***>
Sent: Thursday, June 17, 2021 12:28 PM
To: GEOS-ESM/GEOSadas ***@***.***>
Cc: Stassi, Joe (GSFC-610.1)[SCIENCE SYSTEMS AND APPLICATIONS INC] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [GEOS-ESM/GEOSadas] Feature/jstassi/#73 integrate radmon into adas (#99)


@gmao-jstassi<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgmao-jstassi&data=04%7C01%7Cjoe.stassi%40nasa.gov%7Ce41481e6f9074b2092fb08d931acee6d%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637595441069876790%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Bh1d1wKmtEiuKYOfW5ovaFiuDn0rIjGUolXb0UedXPI%3D&reserved=0> I think you started this with an old version of GEOSadas as it's trying to change a LOT.

You might have to redo your branch basing it off of develop at present.

**Comment by gmao-jstassi** [comment]
Matt, I need to get off for the day. Can you kill the pull request?

________________________________

**Comment by mathomp4** [comment]
> Matt, I need to get off for the day. Can you kill the pull request?

Sure I can close it.

**Pull request closed without merging**
