### PR TITLE
R21C DAS Candidate

### PR DESCRIPTION
**Pull request by sdrabenh**

### CODE REVIEW

**Comment by sdrabenh** [comment]
@rtodling @elakkraoui I updated this PR to use the new tags in [GEOSana_GridComp](https://github.com/GEOS-ESM/GEOSana_GridComp/releases/tag/v1.5.5-R21C-1) and [GMAO_Shared](https://github.com/GEOS-ESM/GMAO_Shared/releases/tag/v1.7.2%2BR21C_v1.0.0). This PR has been undrafted and is ready for approval, merging and tagging.

**Review by rtodling — APPROVED** [review]
We certainly seem to have a system within a system!

**Comment by elakkraoui** [comment]
Thank you, Ricardo.

Amal


--
Amal El Akkraoui, PhD, PMP (She/Her)
NASA Global Modeling and Assimilation Office
Code 610.1 - Goddard Space Flight Center
P: 301-614-5500 / F: 301-614-6246
E: ***@***.******@***.***>
--


From: rtodling ***@***.***>
Reply-To: GEOS-ESM/GEOSadas ***@***.***>
Date: Thursday, March 7, 2024 at 5:49 AM
To: GEOS-ESM/GEOSadas ***@***.***>
Cc: "EL Akkraoui, Amal (GSFC-6101)" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [GEOS-ESM/GEOSadas] R21C DAS Candidate (PR #268)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



@rtodling approved this pull request.

We certainly seem to have a system within a system!

**Comment by mathomp4** [comment]
I have just merged in https://github.com/GEOS-ESM/GEOSgcm_App/pull/589 from @amolod . Should I make a tag with that update for GEOSgcm_App and update this PR?

**Pull request merged**
